version: '2.1'
networks:
  alfresco-network:
  proxy-network:
    external:
      name: "${PROXY_NETWORK}"
volumes:
  pg-alfresco-volume:
    driver: "${VOLUME_DRIVER}"
  alfresco-index-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 102400
  alfresco-tomcat-logs-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 51200
  alfresco-content-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 1024000
services:
  pg-alfresco:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - alfresco-network
    ports:
     - "5432"
    volumes:
     - pg-alfresco-volume:/var/lib/postgresql/data
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
      POSTGRES_DB: alfresco
  alfresco:
    image: fjudith/alfresco:${ALFRESCO_VERSION}
    mem_reservation: 1024m
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
     - alfresco-network
    ports:
     - "8080"
    volumes:
     - alfresco-index-volume:/alfresco/alf_data
     - alfresco-tomcat-logs-volume:/alfresco/tomcat/logs
     - alfresco-content-volume:/content
    depends_on:
     - "pg-alfresco"
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      CONTENT_STORE: /content
      REVERSE_PROXY_URL: "http://${ALFRESCO_PROXY_HOST}"
      DB_HOST: pg-alfresco
      DB_KIND: postgresql
      DB_NAME: alfresco
      DB_PASSWORD: alfresco
      DB_USERNAME: alfresco
      NOTIFICATION_EMAIL_SITEINVITE: "true"
      LDAP_AUTH_USERNAMEFORMAT: uid=%s,${LDAP_USER_BASEDN}
      LDAP_ENABLED: "true"
      LDAP_GROUP_SEARCHBASE: ${LDAP_GROUP_BASEDN}
      LDAP_SECURITY_CREDENTIALS: ${LDAP_PWD}
      LDAP_SECURITY_PRINCIPAL: ${LDAP_ADMIN}
      LDAP_URL: ${LDAP_URI}
      LDAP_USER_SEARCHBASE: ${LDAP_USER_BASEDN}
      MAIL_HOST: ${SMTP_SERVER}
      MAIL_USERNAME: ${SMTP_USER}
      MAIL_PASSWORD: ${SMTP_PASS}
      MAIL_FROM_DEFAULT: ${SMTP_EMAIL}
      MAIL_SMTP_AUTH: "true"
      CATALINA_OPTS: "-Duser.timezone=${TIMEZONE} -Xms512M -Xmx2048M"
  alfresco-proxy:
    image: openfrontier/alfresco-proxy
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - alfresco-network
     - proxy-network
    ports:
      - "80"
    depends_on:
      - "alfresco"
