version: '3'
networks:
  ci-network:
volumes:
  gerrit-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 51200
  jenkins-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 204800
  nexus-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 102400
  redmine-data-volume:
    driver: "${VOLUME_DRIVER}"
    driver_opts:
      size: 51200
  redmine-log-volume:
    driver: "${VOLUME_DRIVER}"
services:
  gerrit:
    image: openfrontier/gerrit-ci:${GERRIT_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 2m
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "8080"
     - "29418"
    volumes:
     - gerrit-volume:/var/gerrit/review_site
    depends_on:
     - "pg-gerrit"
    environment:
      WEBURL: http://${PROXY_HOST}/gerrit
      HTTPD_LISTENURL: proxy-http://*:8080/gerrit
      DATABASE_TYPE: postgresql
      DB_PORT_5432_TCP_ADDR: pg-gerrit
      DB_PORT_5432_TCP_PORT: 5432
      DB_ENV_POSTGRES_DB: reviewdb
      DB_ENV_POSTGRES_USER: gerrit2
      DB_ENV_POSTGRES_PASSWORD: gerrit
      AUTH_TYPE: ${AUTH_TYPE}
      LDAP_SERVER: ${LDAP_URI}
      LDAP_ACCOUNTBASE: ${LDAP_USER_BASEDN}
      LDAP_GROUPBASE: ${LDAP_GROUP_BASEDN}
      LDAP_ACCOUNTFULLNAME: ${LDAP_ACCOUNTFULLNAME}
      INITIAL_ADMIN_USER: ${CI_INIT_ADMIN}
      INITIAL_ADMIN_PASSWORD: ${CI_INIT_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      USER_EMAIL: ${SMTP_EMAIL}
      GERRIT_INIT_ARGS: --install-plugin=download-commands --install-plugin=replication
      JENKINS_HOST: jenkins
      GITWEB_TYPE: ${GITWEB_TYPE}
  jenkins:
    image: openfrontier/jenkins:${JENKINS_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 2m
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "8080"
     - "50000:50000"
    volumes:
     - jenkins-volume:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai -Djenkins.install.runSetupWizard=false"
      LDAP_SERVER: ${LDAP_URI}
      LDAP_ROOTDN: ${LDAP_USER_BASEDN}
      LDAP_INHIBIT_INFER_ROOTDN: 'false'
      LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: 'false'
      GERRIT_HOST_NAME: gerrit
      GERRIT_FRONT_END_URL: http://${PROXY_HOST}/gerrit
      JENKINS_OPTS: --prefix=/jenkins
      ROOT_URL: http://${PROXY_HOST}/jenkins
  jenkins-agent:
    image: openfrontier/jenkins-swarm-maven-slave:${JENKINS_SWARM_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2m
        max_attempts: 10
        window: 2m
    logging:
      driver: "journald"
    networks:
     - ci-network
    depends_on:
     - "gerrit"
     - "jenkins"
    environment:
      NEXUS_REPO: ${NEXUS_URI}
    command: -master http://jenkins:8080/jenkins/ -labels ${JENKINS_AGENT_LABEL} -mode exclusive -username ${CI_INIT_ADMIN} -password ${CI_INIT_PASSWORD} -executors 1
  nexus:
    image: openfrontier/nexus:${NEXUS_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 2m
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "8081"
    environment:
      CONTEXT_PATH: /nexus
    volumes:
     - nexus-volume:/sonatype-work
  redmine:
    image: sameersbn/redmine:${REDMINE_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 2m
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "80"
    volumes:
     - redmine-log-volume:/var/log/redmine
     - redmine-data-volume:/home/redmine/data
    depends_on:
     - "pg-redmine"
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: pg-redmine
      DB_NAME: redmine
      DB_USER: redmine
      DB_PASS: redmine
      REDMINE_RELATIVE_URL_ROOT: /redmine
      REDMINE_FETCH_COMMITS: hourly
      SMTP_DOMAIN: ${LDAP_DOMAIN}
      SMTP_HOST: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      NGINX_MAX_UPLOAD_SIZE: 200m
