version: '2.1'
networks:
  ci-network:
  proxy-network:
    external:
      name: "${PROXY_NETWORK}"
volumes:
  pg-gerrit-volume:
    driver: "${VOLUME_DRIVER}"
  pg-redmine-volume:
    driver: "${VOLUME_DRIVER}"
  gerrit-volume:
    driver: "${VOLUME_DRIVER}"
  jenkins-volume:
    driver: "${VOLUME_DRIVER}"
  nexus-volume:
    driver: "${VOLUME_DRIVER}"
  redmine-data-volume:
    driver: "${VOLUME_DRIVER}"
  redmine-log-volume:
    driver: "${VOLUME_DRIVER}"
services:
  pg-gerrit:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "5432"
    volumes:
     - pg-gerrit-volume:/var/lib/postgresql/data
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      POSTGRES_USER: gerrit2
      POSTGRES_PASSWORD: gerrit
      POSTGRES_DB: reviewdb
  gerrit:
    image: openfrontier/gerrit-ci:${GERRIT_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
      ci-network:
    ports:
     - "8080"
     - "29418"
    volumes:
     - gerrit-volume:/var/gerrit/review_site
    depends_on:
     - "pg-gerrit"
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      WEBURL: http://${PROXY_HOST}/gerrit
      HTTPD_LISTENURL: proxy-http://*:8080/gerrit
      DATABASE_TYPE: postgresql
      DB_PORT_5432_TCP_ADDR: pg-gerrit
      DB_PORT_5432_TCP_PORT: 5432
      DB_ENV_POSTGRES_DB: reviewdb
      DB_ENV_POSTGRES_USER: gerrit2
      DB_ENV_POSTGRES_PASSWORD: gerrit
      AUTH_TYPE: ${AUTH_TYPE}
      LDAP_SERVER: ${LDAP_URI}
      LDAP_ACCOUNTBASE: ${LDAP_USER_BASEDN}
      LDAP_GROUPBASE: ${LDAP_GROUP_BASEDN}
      LDAP_ACCOUNTFULLNAME: ${LDAP_ACCOUNTFULLNAME}
      INITIAL_ADMIN_USER: ${CI_INIT_ADMIN}
      INITIAL_ADMIN_PASSWORD: ${CI_INIT_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      USER_EMAIL: ${SMTP_EMAIL}
      GERRIT_INIT_ARGS: --install-plugin=download-commands --install-plugin=replication
      JENKINS_HOST: jenkins
      GITWEB_TYPE: ${GITWEB_TYPE}
      OAUTH_BITBUCKET_CLIENT_ID: ${OAUTH_BITBUCKET_CLIENT_ID}
      OAUTH_BITBUCKET_CLIENT_SECRET: ${OAUTH_BITBUCKET_CLIENT_SECRET}
      OAUTH_BITBUCKET_FIX_LEGACY_USER_ID: ${OAUTH_BITBUCKET_FIX_LEGACY_USER_ID}
      OAUTH_ALLOW_EDIT_FULL_NAME: ${OAUTH_ALLOW_EDIT_FULL_NAME}
      OAUTH_ALLOW_REGISTER_NEW_EMAIL: ${OAUTH_ALLOW_REGISTER_NEW_EMAIL}
  jenkins:
    image: openfrontier/jenkins:${JENKINS_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
      ci-network:
    ports:
     - "8080"
     - "50000"
    volumes:
     - jenkins-volume:/var/jenkins_home
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai -Djenkins.install.runSetupWizard=false"
      LDAP_SERVER: ${LDAP_URI}
      LDAP_ROOTDN: ${LDAP_USER_BASEDN}
      LDAP_INHIBIT_INFER_ROOTDN: 'false'
      LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: 'false'
      GERRIT_HOST_NAME: gerrit
      GERRIT_FRONT_END_URL: http://${PROXY_HOST}/gerrit
      JENKINS_OPTS: --prefix=/jenkins
      ROOT_URL: http://${PROXY_HOST}/jenkins
  proxy:
    image: openfrontier/nginx:${NGINX_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
     - proxy-network
    ports:
     - "80"
    depends_on:
     - "gerrit"
     - "jenkins"
     - "nexus"
     - "redmine"
    environment:
      #constraint:node: =${PROXY_NODE}
      SERVER_NAME: ${PROXY_HOST}
      CLIENT_MAX_BODY_SIZE: 200m
  haproxy:
    image: openfrontier/haproxy:${HAPROXY_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "29418"
    depends_on:
     - "gerrit"
    environment:
      constraint:node: =${PROXY_NODE}
      GERRIT_HOST: gerrit
  jenkins-agent:
    image: openfrontier/jenkins-swarm-maven-slave:${JENKINS_SWARM_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
    depends_on:
     - "gerrit"
     - "jenkins"
    environment:
      NEXUS_REPO: ${NEXUS_URI}
    command: -master http://jenkins:8080/jenkins/ -labels ${JENKINS_AGENT_LABEL} -mode exclusive -username ${CI_INIT_ADMIN} -password ${CI_INIT_PASSWORD} -executors 1
  nexus:
    image: openfrontier/nexus:${NEXUS_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "8081"
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      CONTEXT_PATH: /nexus
    volumes:
     - nexus-volume:/sonatype-work
  pg-redmine:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "5432"
    volumes:
     - pg-redmine-volume:/var/lib/postgresql/data
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      POSTGRES_DB: redmine
  redmine:
    image: sameersbn/redmine:${REDMINE_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
      ci-network:
    ports:
     - "80"
    volumes:
     - redmine-log-volume:/var/log/redmine
     - redmine-data-volume:/home/redmine/data
    depends_on:
     - "pg-redmine"
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      DB_ADAPTER: postgresql
      DB_HOST: pg-redmine
      DB_NAME: redmine
      DB_USER: redmine
      DB_PASS: redmine
      REDMINE_RELATIVE_URL_ROOT: /redmine
      REDMINE_FETCH_COMMITS: hourly
      SMTP_DOMAIN: ${RELAY_MYDOMAIN}
      SMTP_HOST: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      NGINX_MAX_UPLOAD_SIZE: 200m
