version: '2'
networks:
  ci-network:
volumes:
  pg-gerrit-volume:
  gerrit-volume:
  jenkins-volume:
  nexus-volume:
services:
  pg-gerrit:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    networks:
     - ci-network
    ports:
     - "5432"
    volumes:
     - pg-gerrit-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gerrit2
      POSTGRES_PASSWORD: gerrit
      POSTGRES_DB: reviewdb
  gerrit:
    image: openfrontier/gerrit-ci:${GERRIT_VERSION}
    restart: unless-stopped
    networks:
     - ci-network
    ports:
     - "8080"
     - "29418"
    volumes:
     - gerrit-volume:/var/gerrit/review_site
    depends_on:
     - "pg-gerrit"
    environment:
      WEBURL: http://${PROXY_HOST}/gerrit
      HTTPD_LISTENURL: proxy-http://*:8080/gerrit
      DATABASE_TYPE: postgresql
      DB_PORT_5432_TCP_ADDR: pg-gerrit
      DB_PORT_5432_TCP_PORT: 5432
      DB_ENV_POSTGRES_DB: reviewdb
      DB_ENV_POSTGRES_USER: gerrit2
      DB_ENV_POSTGRES_PASSWORD: gerrit
      AUTH_TYPE: ${AUTH_TYPE}
      LDAP_SERVER: ${LDAP_URI}
      LDAP_ACCOUNTBASE: ${LDAP_USER_BASEDN}
      LDAP_GROUPBASE: ${LDAP_GROUP_BASEDN}
      LDAP_ACCOUNTFULLNAME: ${LDAP_ACCOUNTFULLNAME}
      INITIAL_ADMIN_USER: ${CI_INIT_ADMIN}
      INITIAL_ADMIN_PASSWORD: ${CI_INIT_PASSWORD}
      GERRIT_INIT_ARGS: --install-plugin=download-commands
      JENKINS_HOST: jenkins
  jenkins:
    restart: unless-stopped
    image: openfrontier/jenkins:${JENKINS_VERSION}
    networks:
     - ci-network
    ports:
     - "8080"
     - "50000:50000"
    volumes:
     - jenkins-volume:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai -Djenkins.install.runSetupWizard=false"
      LDAP_SERVER: ${LDAP_URI}
      LDAP_ROOTDN: ${LDAP_USER_BASEDN}
      LDAP_INHIBIT_INFER_ROOTDN: 'false'
      LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: 'false'
      GERRIT_HOST_NAME: gerrit
      GERRIT_FRONT_END_URL: http://${PROXY_HOST}/gerrit
      JENKINS_OPTS: --prefix=/jenkins
      ROOT_URL: http://${PROXY_HOST}/jenkins
  proxy:
    restart: unless-stopped
    image: openfrontier/nginx:${NGINX_VERSION}
    networks:
     - ci-network
    ports:
     - "80:80"
    depends_on:
     - "gerrit"
     - "jenkins"
     - "nexus"
    environment:
      constraint:node: =${PROXY_NODE}
      SERVER_NAME: ${PROXY_HOST}
      CLIENT_MAX_BODY_SIZE: 200m
  haproxy:
    restart: unless-stopped
    image: openfrontier/haproxy:${HAPROXY_VERSION}
    networks:
     - ci-network
    ports:
     - "29418:29418"
    depends_on:
     - "gerrit"
    environment:
      constraint:node: =${PROXY_NODE}
      GERRIT_HOST: gerrit
  jenkins-agent:
    restart: unless-stopped
    image: openfrontier/jenkins-swarm-maven-slave:${JENKINS_SWARM_VERSION}
    networks:
     - ci-network
    depends_on:
     - "gerrit"
     - "jenkins"
    environment:
      NEXUS_REPO: ${NEXUS_URI}
    command: -master http://jenkins:8080/jenkins/ -labels ${JENKINS_AGENT_LABEL} -mode exclusive -username ${CI_INIT_ADMIN} -password ${CI_INIT_PASSWORD} -executors 1
  nexus:
    restart: unless-stopped
    image: openfrontier/nexus:${NEXUS_VERSION}
    networks:
     - ci-network
    ports:
     - "8081"
    environment:
      CONTEXT_PATH: /nexus
    volumes:
     - nexus-volume:/sonatype-work
  ldap-ssp:
    image: openfrontier/ldap-ssp:${SSP_VERSION}
    restart: unless-stopped
    networks:
     - ci-network
    ports:
     - "80"
    environment:
      LDAP_URL: ${LDAP_URI}
      LDAP_BASE: ${LDAP_USER_BASEDN}
      LDAP_BINDDN: ${LDAP_ADMIN}
      LDAP_BINDPW: ${LDAP_PWD}
      SMTP_HOST: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${SMTP_EMAIL}
