version: '2.1'
networks:
  ldap-network:
volumes:
  openldap-etc-volume:
    driver: "${VOLUME_DRIVER}"
  openldap-repo-volume:
    driver: "${VOLUME_DRIVER}"
  lam-config-volume:
    driver: "${VOLUME_DRIVER}"
  smtp-relay-volume:
    driver: "${VOLUME_DRIVER}"
services:
  openldap:
    image: openfrontier/openldap-server
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "389"
    volumes:
     - openldap-etc-volume:/etc/ldap
     - openldap-repo-volume:/var/lib/ldap
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      SLAPD_PASSWORD: ${LDAP_PWD}
      SLAPD_DOMAIN: ${LDAP_DOMAIN}
      SLAPD_ADDITIONAL_SCHEMAS: ppolicy
      SLAPD_ADDITIONAL_MODULES: ppolicy
      DEBUG_LEVEL: 256
  lam:
    image: openfrontier/lam:${LAM_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "80"
    volumes:
     - lam-config-volume:/var/www/html/lam/config
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      LDAP_URL: ${LDAP_URI}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_DN: ${LDAP_DOMAIN}
      USER_DN: ${LDAP_USER_BASEDN}
      GROUP_DN: ${LDAP_GROUP_BASEDN}
  ssp:
    image: openfrontier/ldap-ssp:${SSP_VERSION}
    restart: on-failure:10
    logging:
      driver: "journald"
    networks:
      ldap-network:
    ports:
     - "80"
    environment:
      LDAP_URL: ${LDAP_URI}
      LDAP_BASE: ${LDAP_USER_BASEDN}
      LDAP_BINDDN: ${LDAP_ADMIN}
      LDAP_BINDPW: ${LDAP_PWD}
      SMTP_HOST: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_AUTH: ${SMTP_AUTH}
      MAIL_FROM: ${SMTP_EMAIL}
      NOTIFY_ON_CHANGE: ${NOTIFY_ON_CHANGE}
      PWD_MIN_LENGTH: ${PWD_MIN_LENGTH}
      PWD_MAX_LENGTH: ${PWD_MAX_LENGTH}
      PWD_MIN_LOWER: ${PWD_MIN_LOWER}
      PWD_MIN_UPPER: ${PWD_MIN_UPPER}
      PWD_MIN_DIGIT: ${PWD_MIN_DIGIT}
      PWD_MIN_SPECIAL: ${PWD_MIN_SPECIAL}
      PWD_SPECIAL_CHARS: ${PWD_SPECIAL_CHARS}
  smtp-relay:
    image: turgon37/smtp-relay
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "25"
    volumes:
     - smtp-relay-volume:/data
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      RELAY_MYDOMAIN: ${RELAY_MYDOMAIN}
      RELAY_HOST: ${RELAY_HOST}
  ldap-haproxy:
    image: qiuranke/docker-haproxy
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "389:389"
     - "25:25"
    depends_on:
     - "openldap"
     - "smtp-relay"
    environment:
      constraint:node: =${PROXY_NODE}
      OPENLDAP_HOST: openldap
      MAIL_HOST: smtp-relay
  ldap-proxy:
    image: qiuranke/docker-ldap-proxy
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "80:80"
    depends_on:
     - "lam"
     - "ssp"
    environment:
      constraint:node: =${PROXY_NODE}
      SERVER_NAME: ${PROXY_HOST}
      CLIENT_MAX_BODY_SIZE: 200m
      LAM_HOST: lam
      SSP_HOST: ssp
