version: '2.1'
networks:
  ldap-network:
volumes:
  openldap-etc-volume:
    driver: "${VOLUME_DRIVER}"
  openldap-repo-volume:
    driver: "${VOLUME_DRIVER}"
  lam-config-volume:
    driver: "${VOLUME_DRIVER}"
services:
  openldap:
    image: openfrontier/openldap-server
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "389"
    volumes:
     - openldap-etc-volume:/etc/ldap
     - openldap-repo-volume:/var/lib/ldap
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      SLAPD_PASSWORD: ${LDAP_PWD}
      SLAPD_DOMAIN: ${LDAP_DOMAIN}
      SLAPD_ADDITIONAL_SCHEMAS: ppolicy
      SLAPD_ADDITIONAL_MODULES: ppolicy
      DEBUG_LEVEL: 256
  lam:
    image: openfrontier/lam:${LAM_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "${LAM_PORT}:80"
    volumes:
     - lam-config-volume:/var/www/html/lam/config
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      LDAP_URL: ${LDAP_URI}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_DN: ${LDAP_DOMAIN}
      USER_DN: ${LDAP_USER_BASEDN}
      GROUP_DN: ${LDAP_GROUP_BASEDN}
