version: '2.1'
networks:
  ldap-network:
  proxy-network:
    external:
      name: "${PROXY_NETWORK}"
volumes:
  lam-config-volume:
    driver: "${VOLUME_DRIVER}"
  smtp-relay-volume:
    driver: "${VOLUME_DRIVER}"
services:
  lam:
    image: openfrontier/lam:${LAM_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "80"
    volumes:
     - lam-config-volume:/var/www/html/lam/config
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      LDAP_URL: ldap://ldap-haproxy
      LDAP_PORT: 389
      LDAP_ADMIN: ${LDAP_ADMIN}
      SLAPD_DN: ${LDAP_BASEDN}
      USER_DN: ${LDAP_USER_BASEDN}
      GROUP_DN: ${LDAP_GROUP_BASEDN}
  ssp:
    image: openfrontier/ldap-ssp:${SSP_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "80"
    environment:
      LDAP_URL: ldap://ldap-haproxy
      LDAP_BASE: ${LDAP_USER_BASEDN}
      LDAP_BINDDN: ${LDAP_ADMIN}
      LDAP_BINDPW: ${LDAP_PWD}
      SMTP_HOST: smtp-relay
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_AUTH: ${SMTP_AUTH}
      MAIL_FROM: ${SMTP_EMAIL}
      NOTIFY_ON_CHANGE: ${NOTIFY_ON_CHANGE}
      PWD_MIN_LENGTH: ${PWD_MIN_LENGTH}
      PWD_MAX_LENGTH: ${PWD_MAX_LENGTH}
      PWD_MIN_LOWER: ${PWD_MIN_LOWER}
      PWD_MIN_UPPER: ${PWD_MIN_UPPER}
      PWD_MIN_DIGIT: ${PWD_MIN_DIGIT}
      PWD_MIN_SPECIAL: ${PWD_MIN_SPECIAL}
      PWD_SPECIAL_CHARS: ${PWD_SPECIAL_CHARS}
  smtp-relay:
    image: turgon37/smtp-relay
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
    ports:
     - "25"
    volumes:
     - smtp-relay-volume:/data
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      RELAY_MYDOMAIN: ${RELAY_MYDOMAIN}
      RELAY_HOST: ${RELAY_HOST}
  ldap-haproxy:
    image: openfrontier/haproxy-etcd:${HAPROXY_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
     - ldap-network
    ports:
     - "389:389"
     - "25:25"
    environment:
      constraint:node: =${LDAP_PROXY_NODE}
      ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  ldap-proxy:
    image: openfrontier/ldap-proxy
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ldap-network
     - proxy-network
    ports:
     - "80"
    depends_on:
     - "lam"
     - "ssp"
    environment:
      #constraint:node: =${LDAP_PROXY_NODE}
      SERVER_NAME: ${LDAP_PROXY_HOST}
      CLIENT_MAX_BODY_SIZE: 200m
      LAM_HOST: lam
      SSP_HOST: ssp
