version: '2.1'
networks:
  ci-network:
volumes:
  smtp-relay-volume:
    driver: "${VOLUME_DRIVER}"
services:
  smtp-relay:
    image: turgon37/smtp-relay
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - ci-network
    ports:
     - "25"
    volumes:
     - smtp-relay-volume:/data
    environment:
      constraint:volume.driver: =${VOLUME_DRIVER}
      RELAY_MYDOMAIN: ${RELAY_MYDOMAIN}
      RELAY_HOST: ${RELAY_HOST}
