version: '2.1'
networks:
  proxy-network:
services:
  proxy00:
    image: openfrontier/nginx-etcd:latest
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
     - proxy-network
    ports:
     - "80:80"
    environment:
      constraint:node: =${PROXY_NODE}
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
